<div class="ai2html" id="gu-oceans-box">
  <!-- Generated by ai2html v0.65.1-guardian-customized-v11 - 2020-02-21 - 16:06 --><!-- ai file: oceans.ai -->
  <!-- Artboard: mobile_300 -->
  <div
    class="gu-artboard gu-artboard-v3"
    data-max-width="319"
    data-min-width="300"
    id="gu-oceans-mobile_300"
  >
    <div
      class="gu-aiBackgroundImg"
      id="gu-ai0-0"
      style="width:100%;padding-bottom:281.24%; background-image:url(https://interactive.guim.co.uk/atoms/2020/02/frontline-episode-4/v/1582496332421/assets/oceans-mobile_300.png);"
    ></div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-1"
      style="top:0.4741%;left:2.2491%;width:98.3333%;"
    >
      <p class="gu-pstyle0">
        Sea surface warming over time in Australia's southern oceans
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-2"
      style="top:6.8743%;left:2.0083%;width:93%;"
    >
      <p>
        This chart shows the annual sea surface temperature anomaly for
        Australia’s southern regions. Sea surface temperature anomaly is a
        measure of how much the temperature in a given year is different from
        the average temperature over the period 1961–1990
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai0-3"
      style="top:24.7337%;margin-top:-6.7px;right:92.4705%;width:21px;"
    >
      <p class="gu-pstyle1">+0.6</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai0-4"
      style="top:28.882%;margin-top:-6.7px;right:92.6688%;width:8px;"
    >
      <p class="gu-pstyle1">0</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai0-5"
      style="top:34.8082%;margin-top:-6.7px;right:92.8553%;width:19px;"
    >
      <p class="gu-pstyle1">-0.8</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="2010"
      style="top:37.2971%;margin-top:-6.7px;right:7.5591%;width:22px;"
    >
      <p class="gu-pstyle1">2010</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1900"
      style="top:37.4157%;margin-top:-6.7px;right:87.9294%;width:23px;"
    >
      <p class="gu-pstyle1">1900</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1900"
      style="top:37.4157%;margin-top:-6.7px;right:65.755%;width:22px;"
    >
      <p class="gu-pstyle1">1930</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1900"
      style="top:37.4157%;margin-top:-6.7px;right:21.7253%;width:22px;"
    >
      <p class="gu-pstyle1">1990</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1960"
      style="top:37.4157%;margin-top:-6.7px;right:44.0197%;width:22px;"
    >
      <p class="gu-pstyle1">1960</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-11"
      style="top:39.9423%;left:1.8438%;width:101%;"
    >
      <p class="gu-pstyle2">
        Source: Bureau of Meteorology. Graphic produced by: Jack Zhao/Small
        Multiples
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-12"
      style="top:45.2758%;left:2.273%;width:94.6667%;"
    >
      <p class="gu-pstyle3">
        During a marine heatwave, some areas can be almost 3C warmer than they
        were 25 years ago
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-13"
      style="top:57.7207%;left:2.1718%;width:94.3333%;"
    >
      <p>
        This map shows the average sea surface temperature in the summer of
        1993-94, with an average across the whole region of 15.8C. This compares
        with an average of 18.4C for the summer of 2015-16
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-14"
      style="top:71.4694%;left:2.5816%;width:22.6667%;"
    >
      <p class="gu-pstyle4">1994</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-15"
      style="top:71.5879%;left:45.0476%;width:21.3333%;"
    >
      <p class="gu-pstyle4">2016</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-16"
      style="top:73.0102%;left:95.3384%;margin-left:-4.5%;width:9%;"
    >
      <p class="gu-pstyle5">21C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai0-17"
      style="top:76.1731%;margin-top:-4.7px;left:3.755%;width:34px;"
    >
      <p class="gu-pstyle6">Bass Strait</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-18"
      style="top:76.3289%;right:8.4091%;width:5.3333%;"
    >
      <p class="gu-pstyle7">20C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-19"
      style="top:78.9364%;right:8.4091%;width:5.3333%;"
    >
      <p class="gu-pstyle7">19C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-20"
      style="top:81.5439%;right:8.3532%;width:6%;"
    >
      <p class="gu-pstyle7">18C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai0-21"
      style="top:81.9808%;margin-top:-4.7px;left:26.6592%;width:39px;"
    >
      <p class="gu-pstyle6">Tasman Sea</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-22"
      style="top:81.8995%;left:11.0676%;margin-left:-8.3333%;width:16.6667%;"
    >
      <p class="gu-pstyle8">Tasmania</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-23"
      style="top:84.0329%;right:8.3532%;width:6%;"
    >
      <p class="gu-pstyle7">17C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-24"
      style="top:86.6404%;right:8.4091%;width:5.3333%;"
    >
      <p class="gu-pstyle7">16C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-25"
      style="top:90.6702%;right:6.8821%;width:5.3333%;"
    >
      <p class="gu-pstyle7">15C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-26"
      style="top:92.5665%;left:95.6438%;margin-left:-4.5%;width:9%;"
    >
      <p class="gu-pstyle5">14C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai0-27"
      style="top:95.0555%;left:3.1272%;width:92.6667%;"
    >
      <p class="gu-pstyle9">
        Source: Csiro. Graphic produced by: Jack Zhao/Small Multiples
      </p>
    </div>
  </div>
  <!-- Artboard: supporting_380 -->
  <div
    class="gu-artboard gu-artboard-v3"
    data-max-width="479"
    data-min-width="320"
    id="gu-oceans-supporting_380"
  >
    <div
      class="gu-aiBackgroundImg"
      id="gu-ai1-0"
      style="width:100%;padding-bottom:263.66%; background-image:url(https://interactive.guim.co.uk/atoms/2020/02/frontline-episode-4/v/1582496332421/assets/oceans-supporting_380.png);"
    ></div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-1"
      style="top:0.5926%;left:1.3174%;width:92.1875%;"
    >
      <p class="gu-pstyle0">
        Sea surface warming over time in Australia's southern oceans
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-2"
      style="top:6.9929%;left:1.4042%;width:94.6875%;"
    >
      <p>
        This chart shows the annual sea surface temperature anomaly for
        Australia’s southern regions. Sea surface temperature anomaly is a
        measure of how much the temperature in a given year is different from
        the average temperature over the period 1961–1990
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai1-3"
      style="top:23.667%;margin-top:-6.7px;right:93.1071%;width:23px;"
    >
      <p class="gu-pstyle1">+0.6</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai1-4"
      style="top:27.6968%;margin-top:-6.7px;right:93.5329%;width:8px;"
    >
      <p class="gu-pstyle1">0</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai1-5"
      style="top:33.7415%;margin-top:-6.7px;right:93.4416%;width:21px;"
    >
      <p class="gu-pstyle1">-0.8</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="2010"
      style="top:36.2304%;margin-top:-6.7px;right:5.6326%;width:24px;"
    >
      <p class="gu-pstyle1">2010</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1900"
      style="top:36.3489%;margin-top:-6.7px;right:88.4952%;width:25px;"
    >
      <p class="gu-pstyle1">1900</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1900"
      style="top:36.3489%;margin-top:-6.7px;right:65.6108%;width:24px;"
    >
      <p class="gu-pstyle1">1930</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1900"
      style="top:36.3489%;margin-top:-6.7px;right:20.2327%;width:24px;"
    >
      <p class="gu-pstyle1">1990</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1960"
      style="top:36.3489%;margin-top:-6.7px;right:43.2098%;width:24px;"
    >
      <p class="gu-pstyle1">1960</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-11"
      style="top:38.8756%;left:2.1875%;width:94.6875%;"
    >
      <p class="gu-pstyle2">
        Source: Bureau of Meteorology. Graphic produced by: Jack Zhao/Small
        Multiples
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-12"
      style="top:43.8535%;left:1.3398%;width:96.5625%;"
    >
      <p class="gu-pstyle3">
        During a marine heatwave, some areas can be almost 3C warmer than they
        were 25 years ago
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-13"
      style="top:56.654%;left:1.4626%;width:94.375%;"
    >
      <p>
        This map shows the average sea surface temperature in the summer of
        1993-94, with an average across the whole region of 15.8C. This compares
        with an average of 18.4C for the summer of 2015-16
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-14"
      style="top:68.6249%;left:1.6292%;width:23.125%;"
    >
      <p class="gu-pstyle4">1994</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-15"
      style="top:68.7434%;left:45.0843%;width:21.875%;"
    >
      <p class="gu-pstyle4">2016</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-16"
      style="top:70.4027%;left:96.4729%;margin-left:-4.5312%;width:9.0625%;"
    >
      <p class="gu-pstyle5">21C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai1-17"
      style="top:73.6649%;margin-top:-4.5px;left:2.8299%;width:37px;"
    >
      <p class="gu-pstyle6">Bass Strait</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-18"
      style="top:74.0769%;right:7.1208%;width:5.625%;"
    >
      <p class="gu-pstyle7">20C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-19"
      style="top:76.803%;right:7.1208%;width:5.625%;"
    >
      <p class="gu-pstyle7">19C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-20"
      style="top:79.6475%;right:7.1208%;width:6.25%;"
    >
      <p class="gu-pstyle7">18C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai1-21"
      style="top:80.0651%;margin-top:-4.5px;left:26.2674%;width:42px;"
    >
      <p class="gu-pstyle6">Tasman Sea</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-22"
      style="top:80.0031%;left:10.3792%;margin-left:-8.5937%;width:17.1875%;"
    >
      <p class="gu-pstyle8">Tasmania</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-23"
      style="top:82.3736%;right:7.1208%;width:6.25%;"
    >
      <p class="gu-pstyle7">17C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-24"
      style="top:85.2181%;right:7.1208%;width:5.625%;"
    >
      <p class="gu-pstyle7">16C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-25"
      style="top:89.6035%;right:5.5583%;width:5.625%;"
    >
      <p class="gu-pstyle7">15C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-26"
      style="top:91.7369%;left:96.7854%;margin-left:-4.5312%;width:9.0625%;"
    >
      <p class="gu-pstyle5">14C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai1-27"
      style="top:94.3444%;left:2.1875%;width:94.6875%;"
    >
      <p class="gu-pstyle2">
        Source: Csiro. Graphic produced by: Jack Zhao/Small Multiples
      </p>
    </div>
  </div>
  <!-- Artboard: mobileLandscape_460 -->
  <div
    class="gu-artboard gu-artboard-v3"
    data-max-width="779"
    data-min-width="480"
    id="gu-oceans-mobileLandscape_460"
  >
    <div
      class="gu-aiBackgroundImg"
      id="gu-ai2-0"
      style="width:100%;padding-bottom:174.58%; background-image:url(https://interactive.guim.co.uk/atoms/2020/02/frontline-episode-4/v/1582496332421/assets/oceans-mobileLandscape_460.png);"
    ></div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-1"
      style="top:1.074%;left:1.1683%;width:97.5%;"
    >
      <p class="gu-pstyle0">
        Sea surface warming over time in Australia's southern oceans
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-2"
      style="top:7.8759%;left:1.4345%;width:97.2917%;"
    >
      <p>
        This chart shows the annual sea surface temperature anomaly for
        Australia’s southern regions. Sea surface temperature anomaly is a
        measure of how much the temperature in a given year is different from
        the average temperature over the period 1961–1990
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai2-3"
      style="top:19.0715%;margin-top:-7.8px;right:94.1987%;width:27px;"
    >
      <p class="gu-pstyle1">+0.6</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai2-4"
      style="top:23.7254%;margin-top:-7.8px;right:94.2824%;width:10px;"
    >
      <p class="gu-pstyle1">0</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai2-5"
      style="top:30.5273%;margin-top:-7.8px;right:94.3359%;width:25px;"
    >
      <p class="gu-pstyle1">-0.8</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1960"
      style="top:33.6299%;margin-top:-7.8px;right:44.8724%;width:29px;"
    >
      <p class="gu-pstyle1">1960</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1900"
      style="top:33.6299%;margin-top:-7.8px;right:90.7584%;width:29px;"
    >
      <p class="gu-pstyle1">1900</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1900"
      style="top:33.6299%;margin-top:-7.8px;right:67.7177%;width:28px;"
    >
      <p class="gu-pstyle1">1930</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1900"
      style="top:33.6299%;margin-top:-7.8px;right:22.027%;width:29px;"
    >
      <p class="gu-pstyle1">1990</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="2010"
      style="top:33.6299%;margin-top:-7.8px;right:6.6438%;width:29px;"
    >
      <p class="gu-pstyle1">2010</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai2-11"
      style="top:39.3371%;margin-top:-8.6px;left:1.0361%;width:432px;"
    >
      <p class="gu-pstyle2">
        Source: Bureau of Meteorology. Graphic produced by: Jack Zhao/Small
        Multiples
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-12"
      style="top:42.4821%;left:1.5031%;width:96.6667%;"
    >
      <p class="gu-pstyle3">
        During a marine heatwave, some areas can be almost 3C warmer than they
        were 25 years ago
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-13"
      style="top:50%;left:1.7933%;width:93.9583%;"
    >
      <p>
        This map shows the average sea surface temperature in the summer of
        1993-94, with an average across the whole region of 15.8C. This compares
        with an average of 18.4C for the summer of 2015-16
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-14"
      style="top:58.7112%;left:2.582%;width:14.7917%;"
    >
      <p class="gu-pstyle4">1994</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-15"
      style="top:58.7112%;left:46.424%;width:13.9583%;"
    >
      <p class="gu-pstyle4">2016</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-16"
      style="top:60.2625%;left:95.3517%;margin-left:-2.9167%;width:5.8333%;"
    >
      <p class="gu-pstyle5">21C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai2-17"
      style="top:64.7377%;margin-top:-5.5px;left:5.4894%;width:46px;"
    >
      <p class="gu-pstyle6">Bass Strait</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-18"
      style="top:65.7518%;right:7.0117%;width:3.5417%;"
    >
      <p class="gu-pstyle7">20C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-19"
      style="top:70.0477%;right:7.0117%;width:3.5417%;"
    >
      <p class="gu-pstyle7">19C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-20"
      style="top:74.3437%;right:6.9935%;width:3.9583%;"
    >
      <p class="gu-pstyle7">18C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai2-21"
      style="top:75.5969%;margin-top:-5.5px;left:30.1942%;width:52px;"
    >
      <p class="gu-pstyle6">Tasman Sea</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-22"
      style="top:75.2983%;left:10.933%;margin-left:-6.4583%;width:12.9167%;"
    >
      <p class="gu-pstyle8">Tasmania</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-23"
      style="top:78.7589%;right:6.9935%;width:3.9583%;"
    >
      <p class="gu-pstyle7">17C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-24"
      style="top:83.0549%;right:7.0117%;width:3.5417%;"
    >
      <p class="gu-pstyle7">16C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-25"
      style="top:87.3508%;right:7.0117%;width:3.5417%;"
    >
      <p class="gu-pstyle7">15C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai2-26"
      style="top:92.9594%;left:95.3517%;margin-left:-2.9167%;width:5.8333%;"
    >
      <p class="gu-pstyle5">14C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai2-27"
      style="top:97.213%;margin-top:-8.6px;left:1.8694%;width:335px;"
    >
      <p class="gu-pstyle2">
        Source: Csiro. Graphic produced by: Jack Zhao/Small Multiples
      </p>
    </div>
  </div>
  <!-- Artboard: inArticle_620 -->
  <div
    class="gu-artboard gu-artboard-v3"
    data-min-width="780"
    id="gu-oceans-inArticle_620"
  >
    <div
      class="gu-aiBackgroundImg"
      id="gu-ai3-0"
      style="width:100%;padding-bottom:127.18%; background-image:url(https://interactive.guim.co.uk/atoms/2020/02/frontline-episode-4/v/1582496332421/assets/oceans-inArticle_620.png);"
    ></div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-1"
      style="top:1.1089%;left:0.8991%;width:96.6667%;"
    >
      <p class="gu-pstyle0">
        Sea surface warming over time in Australia's southern oceans
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-2"
      style="top:4.4355%;left:0.9307%;width:97.3077%;"
    >
      <p>
        This chart shows the annual sea surface temperature anomaly for
        Australia’s southern regions. Sea surface temperature anomaly is a
        measure of how much the temperature in a given year is different from
        the average temperature over the period 1961–1990
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai3-3"
      style="top:12.8171%;margin-top:-23.1px;right:9.5295%;width:108px;"
    >
      <p class="gu-pstyle1">2013</p>
      <p class="gu-pstyle2">Hottest year</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai3-4"
      style="top:18.7318%;margin-top:-7.8px;right:96.1396%;width:27px;"
    >
      <p class="gu-pstyle3">+0.6</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai3-5"
      style="top:22.5624%;margin-top:-7.8px;right:96.2658%;width:10px;"
    >
      <p class="gu-pstyle3">0</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai3-6"
      style="top:28.2076%;margin-top:-7.8px;right:96.2963%;width:25px;"
    >
      <p class="gu-pstyle3">-0.8</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1900"
      style="top:30.6269%;margin-top:-7.8px;left:3.2129%;width:29px;"
    >
      <p class="gu-pstyle4">1900</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1900"
      style="top:30.6269%;margin-top:-7.8px;left:25.498%;width:28px;"
    >
      <p class="gu-pstyle4">1930</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1960"
      style="top:30.6269%;margin-top:-7.8px;left:47.6792%;width:29px;"
    >
      <p class="gu-pstyle4">1960</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="1900"
      style="top:30.6269%;margin-top:-7.8px;left:69.8709%;width:29px;"
    >
      <p class="gu-pstyle4">1990</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="2010"
      style="top:30.6269%;margin-top:-7.8px;left:84.7606%;width:29px;"
    >
      <p class="gu-pstyle4">2010</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai3-12"
      style="top:35.3473%;margin-top:-8.6px;left:1.2837%;width:432px;"
    >
      <p class="gu-pstyle5">
        Source: Bureau of Meteorology. Graphic produced by: Jack Zhao/Small
        Multiples
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-13"
      style="top:37.8024%;left:1.1941%;width:98.8462%;"
    >
      <p class="gu-pstyle6">
        During a marine heatwave, some areas can be almost 3C warmer than they
        were 25 years ago
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-14"
      style="top:43.9516%;left:1.4505%;width:97.3077%;"
    >
      <p>
        This map shows the average sea surface temperature in the summer of
        1993-94, with an average across the whole region of 15.8C. This compares
        with an average of 18.4C for the summer of 2015-16
      </p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-15"
      style="top:48.8911%;left:1.6808%;width:14.6154%;"
    >
      <p class="gu-pstyle7">1994</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-16"
      style="top:48.8911%;left:45.0789%;width:13.8462%;"
    >
      <p class="gu-pstyle7">2016</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-17"
      style="top:51.2097%;left:93.5087%;margin-left:-2.8846%;width:5.7692%;"
    >
      <p class="gu-pstyle8">21C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai3-18"
      style="top:57.2123%;margin-top:-9.5px;left:4.5589%;width:73px;"
    >
      <p class="gu-pstyle9">Bass Strait</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-19"
      style="top:58.5685%;right:8.7444%;width:3.5897%;"
    >
      <p class="gu-pstyle3">20C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-20"
      style="top:64.5161%;right:8.7444%;width:3.5897%;"
    >
      <p class="gu-pstyle3">19C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-21"
      style="top:70.3629%;right:8.7542%;width:3.9744%;"
    >
      <p class="gu-pstyle3">18C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai3-22"
      style="top:71.9301%;margin-top:-9.5px;left:29.0135%;width:82px;"
    >
      <p class="gu-pstyle9">Tasman Sea</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-23"
      style="top:71.4718%;left:9.9005%;margin-left:-6.3462%;width:12.6923%;"
    >
      <p class="gu-pstyle10">Tasmania</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-24"
      style="top:76.2097%;right:8.7542%;width:3.9744%;"
    >
      <p class="gu-pstyle3">17C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-25"
      style="top:82.1573%;right:8.7444%;width:3.5897%;"
    >
      <p class="gu-pstyle3">16C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-26"
      style="top:88.004%;right:8.7444%;width:3.5897%;"
    >
      <p class="gu-pstyle3">15C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs"
      id="gu-ai3-27"
      style="top:95.5645%;left:93.5087%;margin-left:-2.8846%;width:5.7692%;"
    >
      <p class="gu-pstyle8">14C</p>
    </div>
    <div
      class="gu-graphic gu-aiAbs gu-aiPointText"
      id="gu-ai3-28"
      style="top:98.7545%;margin-top:-8.6px;left:1.6808%;width:335px;"
    >
      <p class="gu-pstyle5">
        Source: Csiro. Graphic produced by: Jack Zhao/Small Multiples
      </p>
    </div>
  </div>
  <!-- End ai2html - 2020-02-21 - 16:06 -->
</div>

<style lang="scss">
  .interactive-wrapper .blocks .block .multimedia {
    margin: auto;
    max-width: 780px;
  }
  @media (max-width: 19.99em) {
    .interactive-wrapper .blocks .block .multimedia {
      padding: 10px;
    }
  }
  @media (min-width: 20em) and (max-width: 29.99em) {
    .interactive-wrapper .blocks .block .multimedia {
      padding-top: 40px;
      padding-bottom: 40px;
      padding-left: 10px;
      padding-right: 10px;
    }
  }
  @media (min-width: 30em) and (max-width: 46.24em) {
    .interactive-wrapper .blocks .block .multimedia {
      padding: 40px;
    }
  }
  @media (min-width: 46.25em) and (max-width: 61.24em) {
    .interactive-wrapper .blocks .block .multimedia {
      padding: 40px;
    }
  }
  .interactive-wrapper .blocks .block .graphic-container {
    width: 100%;
    display: inline-block;
    background-color: rgba(0, 0, 0, 0.5);
  }
  .ai2html {
    margin: auto;
    max-width: 620px;
    text-align: center;

    @include mq($until: mobile) {
      padding: 10px;
    }

    @include mq($from: mobile, $until: mobileLandscape) {
      padding: 40px 10px;
    }

    @include mq($from: mobileLandscape, $until: tablet) {
      padding: 40px;
    }

    @include mq($from: tablet, $until: desktop) {
      padding: 40px;
    }
  }

  /*! CSS Used from: Embedded ; media=screen, print */

  @media screen, print {
    #gu-oceans-box .gu-artboard p {
      margin: 0;
    }
    .gu-aiAbs {
      position: absolute;
    }
    .gu-aiBackgroundImg {
      display: block;
      position: relative;
      background-repeat: no-repeat;
      background-size: cover;
      width: 100% !important;
    }
    .gu-aiPointText p {
      white-space: nowrap;
    }
  }
  /*! CSS Used from: Embedded ; media=screen, print */

  @media screen, print {
    #gu-oceans-mobile_300 {
      display: block;
    }
    #gu-oceans-supporting_380 {
      display: none;
    }
    #gu-oceans-mobileLandscape_460 {
      display: none;
    }
    #gu-oceans-inArticle_620 {
      display: none;
    }
    @media (min-width: 319.5px) {
      #gu-oceans-mobile_300 {
        display: none;
      }
      #gu-oceans-supporting_380 {
        display: block;
      }
      #gu-oceans-mobileLandscape_460 {
        display: none;
      }
      #gu-oceans-inArticle_620 {
        display: none;
      }
    }
    @media (min-width: 479.5px) {
      #gu-oceans-mobile_300 {
        display: none;
      }
      #gu-oceans-supporting_380 {
        display: none;
      }
      #gu-oceans-mobileLandscape_460 {
        display: block;
      }
      #gu-oceans-inArticle_620 {
        display: none;
      }
    }
    @media (min-width: 779.5px) {
      #gu-oceans-mobile_300 {
        display: none;
      }
      #gu-oceans-supporting_380 {
        display: none;
      }
      #gu-oceans-mobileLandscape_460 {
        display: none;
      }
      #gu-oceans-inArticle_620 {
        display: block;
      }
    }
  }
  /*! CSS Used from: Embedded ; media=screen, print */

  @media screen, print {
    #gu-oceans-mobile_300 {
      position: relative;
      overflow: hidden;
    }
    #gu-oceans-mobile_300 p {
      font-family: "Guardian Text Egyptian Web", Georgia, serif;
      font-weight: 400;
      font-size: 14px;
      line-height: 18px;
      filter: alpha(opacity=100);
      -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
      opacity: 1;
      text-align: left;
      color: rgb(234, 234, 234);
      text-transform: none;
      padding-bottom: 0;
      padding-top: 0;
      mix-blend-mode: normal;
      font-style: normal;
    }
    #gu-oceans-mobile_300 .gu-pstyle0 {
      font-weight: 800;
      font-size: 18px;
      line-height: 22px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-mobile_300 .gu-pstyle1 {
      font-size: 10px;
      line-height: 12px;
      text-align: right;
      color: rgb(204, 204, 204);
    }
    #gu-oceans-mobile_300 .gu-pstyle2 {
      font-family: "Guardian Text Sans Web", Arial, sans-serif;
      font-size: 12px;
      line-height: 16px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-mobile_300 .gu-pstyle3 {
      font-family: "GH Guardian Headline", Georgia, serif;
      font-weight: 800;
      font-size: 20px;
      line-height: 24px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-mobile_300 .gu-pstyle4 {
      font-size: 11px;
      line-height: 13px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-mobile_300 .gu-pstyle5 {
      font-weight: 800;
      font-size: 6px;
      line-height: 8px;
      text-align: center;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-mobile_300 .gu-pstyle6 {
      font-weight: 800;
      font-size: 6px;
      line-height: 8px;
      filter: alpha(opacity=80);
      -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=80);
      opacity: 0.8;
      color: rgb(0, 0, 0);
    }
    #gu-oceans-mobile_300 .gu-pstyle7 {
      font-size: 6px;
      line-height: 8px;
      text-align: right;
      color: rgb(204, 204, 204);
    }
    #gu-oceans-mobile_300 .gu-pstyle8 {
      font-weight: 800;
      font-size: 7px;
      line-height: 9px;
      filter: alpha(opacity=80);
      -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=80);
      opacity: 0.8;
      text-align: center;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-mobile_300 .gu-pstyle9 {
      font-family: "Guardian Text Sans Web", Arial, sans-serif;
      font-size: 11px;
      line-height: 15px;
      color: rgb(255, 255, 255);
    }
  }
  /*! CSS Used from: Embedded ; media=screen, print */

  @media screen, print {
    #gu-oceans-supporting_380 {
      position: relative;
      overflow: hidden;
    }
    #gu-oceans-supporting_380 p {
      font-family: "Guardian Text Egyptian Web", Georgia, serif;
      font-weight: 400;
      font-size: 14px;
      line-height: 18px;
      filter: alpha(opacity=100);
      -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
      opacity: 1;
      text-align: left;
      color: rgb(234, 234, 234);
      text-transform: none;
      padding-bottom: 0;
      padding-top: 0;
      mix-blend-mode: normal;
      font-style: normal;
    }
    #gu-oceans-supporting_380 .gu-pstyle0 {
      font-weight: 800;
      font-size: 18px;
      line-height: 22px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-supporting_380 .gu-pstyle1 {
      font-size: 10px;
      line-height: 12px;
      text-align: right;
      color: rgb(204, 204, 204);
    }
    #gu-oceans-supporting_380 .gu-pstyle2 {
      font-family: "Guardian Text Sans Web", Arial, sans-serif;
      font-size: 12px;
      line-height: 16px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-supporting_380 .gu-pstyle3 {
      font-family: "GH Guardian Headline", Georgia, serif;
      font-weight: 800;
      font-size: 20px;
      line-height: 24px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-supporting_380 .gu-pstyle4 {
      font-size: 12px;
      line-height: 14px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-supporting_380 .gu-pstyle5 {
      font-weight: 800;
      font-size: 7px;
      line-height: 8px;
      text-align: center;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-supporting_380 .gu-pstyle6 {
      font-weight: 800;
      font-size: 7px;
      line-height: 8px;
      filter: alpha(opacity=80);
      -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=80);
      opacity: 0.8;
      color: rgb(0, 0, 0);
    }
    #gu-oceans-supporting_380 .gu-pstyle7 {
      font-size: 7px;
      line-height: 8px;
      text-align: right;
      color: rgb(204, 204, 204);
    }
    #gu-oceans-supporting_380 .gu-pstyle8 {
      font-weight: 800;
      font-size: 8px;
      line-height: 10px;
      filter: alpha(opacity=80);
      -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=80);
      opacity: 0.8;
      text-align: center;
      color: rgb(255, 255, 255);
    }
  }
  /*! CSS Used from: Embedded ; media=screen, print */

  @media screen, print {
    #gu-oceans-mobileLandscape_460 {
      position: relative;
      overflow: hidden;
    }
    #gu-oceans-mobileLandscape_460 p {
      font-family: "Guardian Text Egyptian Web", Georgia, serif;
      font-weight: 400;
      font-size: 14px;
      line-height: 18px;
      filter: alpha(opacity=100);
      -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
      opacity: 1;
      text-align: left;
      color: rgb(234, 234, 234);
      text-transform: none;
      padding-bottom: 0;
      padding-top: 0;
      mix-blend-mode: normal;
      font-style: normal;
    }
    #gu-oceans-mobileLandscape_460 .gu-pstyle0 {
      font-weight: 800;
      font-size: 18px;
      line-height: 22px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-mobileLandscape_460 .gu-pstyle1 {
      font-size: 12px;
      line-height: 14px;
      text-align: right;
      color: rgb(204, 204, 204);
    }
    #gu-oceans-mobileLandscape_460 .gu-pstyle2 {
      font-family: "Guardian Text Sans Web", Arial, sans-serif;
      font-size: 12px;
      line-height: 16px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-mobileLandscape_460 .gu-pstyle3 {
      font-family: "GH Guardian Headline", Georgia, serif;
      font-weight: 800;
      font-size: 20px;
      line-height: 24px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-mobileLandscape_460 .gu-pstyle4 {
      font-size: 11px;
      line-height: 13px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-mobileLandscape_460 .gu-pstyle5 {
      font-weight: 800;
      font-size: 7px;
      line-height: 9px;
      text-align: center;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-mobileLandscape_460 .gu-pstyle6 {
      font-weight: 800;
      font-size: 9px;
      line-height: 10px;
      filter: alpha(opacity=80);
      -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=80);
      opacity: 0.8;
      color: rgb(0, 0, 0);
    }
    #gu-oceans-mobileLandscape_460 .gu-pstyle7 {
      font-size: 7px;
      line-height: 9px;
      text-align: right;
      color: rgb(204, 204, 204);
    }
    #gu-oceans-mobileLandscape_460 .gu-pstyle8 {
      font-weight: 800;
      font-size: 11px;
      line-height: 13px;
      filter: alpha(opacity=80);
      -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=80);
      opacity: 0.8;
      text-align: center;
      color: rgb(255, 255, 255);
    }
  }
  /*! CSS Used from: Embedded ; media=screen, print */

  @media screen, print {
    #gu-oceans-inArticle_620 {
      position: relative;
      overflow: hidden;
    }
    #gu-oceans-inArticle_620 p {
      font-family: "Guardian Text Egyptian Web", Georgia, serif;
      font-weight: 400;
      font-size: 14px;
      line-height: 18px;
      filter: alpha(opacity=100);
      -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
      opacity: 1;
      text-align: left;
      color: rgb(234, 234, 234);
      text-transform: none;
      padding-bottom: 0;
      padding-top: 0;
      mix-blend-mode: normal;
      font-style: normal;
    }
    #gu-oceans-inArticle_620 .gu-pstyle0 {
      font-weight: 800;
      font-size: 18px;
      line-height: 22px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-inArticle_620 .gu-pstyle1 {
      font-size: 18px;
      line-height: 22px;
      text-align: right;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-inArticle_620 .gu-pstyle2 {
      font-weight: 800;
      font-size: 18px;
      line-height: 22px;
      text-align: right;
      color: rgb(191, 48, 35);
    }
    #gu-oceans-inArticle_620 .gu-pstyle3 {
      font-size: 12px;
      line-height: 14px;
      text-align: right;
      color: rgb(204, 204, 204);
    }
    #gu-oceans-inArticle_620 .gu-pstyle4 {
      font-size: 12px;
      line-height: 14px;
      color: rgb(204, 204, 204);
    }
    #gu-oceans-inArticle_620 .gu-pstyle5 {
      font-family: "Guardian Text Sans Web", Arial, sans-serif;
      font-size: 12px;
      line-height: 16px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-inArticle_620 .gu-pstyle6 {
      font-family: "GH Guardian Headline", Georgia, serif;
      font-weight: 800;
      font-size: 20px;
      line-height: 24px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-inArticle_620 .gu-pstyle7 {
      font-size: 18px;
      line-height: 22px;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-inArticle_620 .gu-pstyle8 {
      font-weight: 800;
      font-size: 12px;
      line-height: 14px;
      text-align: center;
      color: rgb(255, 255, 255);
    }
    #gu-oceans-inArticle_620 .gu-pstyle9 {
      font-weight: 800;
      line-height: 17px;
      filter: alpha(opacity=80);
      -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=80);
      opacity: 0.8;
      color: rgb(0, 0, 0);
    }
    #gu-oceans-inArticle_620 .gu-pstyle10 {
      font-weight: 800;
      font-size: 18px;
      line-height: 22px;
      filter: alpha(opacity=80);
      -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=80);
      opacity: 0.8;
      text-align: center;
      color: rgb(255, 255, 255);
    }
  }
  /*! CSS Used fontfaces */

  @font-face {
    font-family: "Guardian Text Egyptian Web";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textegyptian/noalts-not-hinted/GuardianTextEgyptian-Regular.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textegyptian/noalts-not-hinted/GuardianTextEgyptian-Regular.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textegyptian/latin1-not-hinted/GuardianTextEgyptian-Regular.ttf)
        format("truetype");
    font-weight: 400;
    font-style: normal;
    font-display: swap;
  }
  @font-face {
    font-family: "Guardian Text Egyptian Web";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textegyptian/noalts-not-hinted/GuardianTextEgyptian-RegularItalic.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textegyptian/latin1-not-hinted/GuardianTextEgyptian-RegularItalic.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textegyptian/latin1-not-hinted/GuardianTextEgyptian-RegularItalic.ttf)
        format("truetype");
    font-weight: 400;
    font-style: italic;
    font-display: swap;
  }
  @font-face {
    font-family: "Guardian Text Egyptian Web";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textegyptian/noalts-not-hinted/GuardianTextEgyptian-Bold.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textegyptian/latin1-not-hinted/GuardianTextEgyptian-Bold.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textegyptian/latin1-not-hinted/GuardianTextEgyptian-Bold.ttf)
        format("truetype");
    font-weight: 700;
    font-style: normal;
    font-display: swap;
  }
  @font-face {
    font-family: "Guardian Text Egyptian Web";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textegyptian/noalts-not-hinted/GuardianTextEgyptian-BoldItalic.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textegyptian/latin1-not-hinted/GuardianTextEgyptian-BoldItalic.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textegyptian/latin1-not-hinted/GuardianTextEgyptian-BoldItalic.ttf)
        format("truetype");
    font-weight: 700;
    font-style: italic;
    font-display: swap;
  }
  @font-face {
    font-family: "Guardian Text Egyptian Web";
    src: url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-Regular.eot");
    src:
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-Regular.eot?#iefix")
        format("embedded-opentype"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-Regular.woff2")
        format("woff2"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-Regular.woff")
        format("woff"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-Regular.ttf")
        format("truetype"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-Regular.svg#GuardianTextEgyptianWeb-Regular")
        format("svg");
    font-weight: 400;
    font-style: normal;
    font-stretch: normal;
  }
  @font-face {
    font-family: "Guardian Text Egyptian Web";
    src: url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-RegularItalic.eot");
    src:
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-RegularItalic.eot?#iefix")
        format("embedded-opentype"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-RegularItalic.woff2")
        format("woff2"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-RegularItalic.woff")
        format("woff"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-RegularItalic.ttf")
        format("truetype"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-RegularItalic.svg#GuardianTextEgyptianWeb-RegularItalic")
        format("svg");
    font-weight: 400;
    font-style: italic;
    font-stretch: normal;
  }
  @font-face {
    font-family: "Guardian Text Egyptian Web";
    src: url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-Medium.eot");
    src:
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-Medium.eot?#iefix")
        format("embedded-opentype"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-Medium.woff2")
        format("woff2"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-Medium.woff")
        format("woff"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-Medium.ttf")
        format("truetype"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextEgyptianWeb/GuardianTextEgyptianWeb-Medium.svg#GuardianTextEgyptianWeb-Medium")
        format("svg");
    font-weight: 700;
    font-style: normal;
    font-stretch: normal;
  }
  @font-face {
    font-family: "Guardian Text Sans Web";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textsans/noalts-not-hinted/GuardianTextSans-Regular.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textsans/noalts-not-hinted/GuardianTextSans-Regular.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textsans/latin1-not-hinted/GuardianTextSans-Regular.ttf)
        format("truetype");
    font-weight: 400;
    font-style: normal;
    font-display: swap;
  }
  @font-face {
    font-family: "Guardian Text Sans Web";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textsans/noalts-not-hinted/GuardianTextSans-RegularItalic.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textsans/latin1-not-hinted/GuardianTextSans-RegularItalic.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textsans/latin1-not-hinted/GuardianTextSans-RegularItalic.ttf)
        format("truetype");
    font-weight: 400;
    font-style: italic;
    font-display: swap;
  }
  @font-face {
    font-family: "Guardian Text Sans Web";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textsans/noalts-not-hinted/GuardianTextSans-Bold.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textsans/latin1-not-hinted/GuardianTextSans-Bold.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textsans/latin1-not-hinted/GuardianTextSans-Bold.ttf)
        format("truetype");
    font-weight: 700;
    font-style: normal;
    font-display: swap;
  }
  @font-face {
    font-family: "Guardian Text Sans Web";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textsans/noalts-not-hinted/GuardianTextSans-BoldItalic.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textsans/latin1-not-hinted/GuardianTextSans-BoldItalic.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-textsans/latin1-not-hinted/GuardianTextSans-BoldItalic.ttf)
        format("truetype");
    font-weight: 700;
    font-style: italic;
    font-display: swap;
  }
  @font-face {
    font-family: "Guardian Text Sans Web";
    src: url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-Regular.eot");
    src:
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-Regular.eot?#iefix")
        format("embedded-opentype"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-Regular.woff2")
        format("woff2"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-Regular.woff")
        format("woff"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-Regular.ttf")
        format("truetype"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-Regular.svg#GuardianTextSansWeb-Regular")
        format("svg");
    font-weight: 400;
    font-style: normal;
    font-stretch: normal;
  }
  @font-face {
    font-family: "Guardian Text Sans Web";
    src: url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-RegularItalic.eot");
    src:
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-RegularItalic.eot?#iefix")
        format("embedded-opentype"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-RegularItalic.woff2")
        format("woff2"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-RegularItalic.woff")
        format("woff"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-RegularItalic.ttf")
        format("truetype"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-RegularItalic.svg#GuardianTextSansWeb-RegularItalic")
        format("svg");
    font-weight: 400;
    font-style: italic;
    font-stretch: normal;
  }
  @font-face {
    font-family: "Guardian Text Sans Web";
    src: url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-Medium.eot");
    src:
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-Medium.eot?#iefix")
        format("embedded-opentype"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-Medium.woff2")
        format("woff2"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-Medium.woff")
        format("woff"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-Medium.ttf")
        format("truetype"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GuardianTextSansWeb/GuardianTextSansWeb-Medium.svg#GuardianTextSansWeb-Medium")
        format("svg");
    font-weight: 700;
    font-style: normal;
    font-stretch: normal;
  }
  @font-face {
    font-family: "GH Guardian Headline";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/noalts-not-hinted/GHGuardianHeadline-Light.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/latin1-not-hinted/GHGuardianHeadline-Light.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/latin1-not-hinted/GHGuardianHeadline-Light.ttf)
        format("truetype");
    font-weight: 300;
    font-style: normal;
    font-display: swap;
  }
  @font-face {
    font-family: "GH Guardian Headline";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/noalts-not-hinted/GHGuardianHeadline-LightItalic.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/latin1-not-hinted/GHGuardianHeadline-LightItalic.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/latin1-not-hinted/GHGuardianHeadline-LightItalic.ttf)
        format("truetype");
    font-weight: 300;
    font-style: italic;
    font-display: swap;
  }
  @font-face {
    font-family: "GH Guardian Headline";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/noalts-not-hinted/GHGuardianHeadline-Medium.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/noalts-not-hinted/GHGuardianHeadline-Medium.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/latin1-not-hinted/GHGuardianHeadline-Medium.ttf)
        format("truetype");
    font-weight: 500;
    font-style: normal;
    font-display: swap;
  }
  @font-face {
    font-family: "GH Guardian Headline";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/noalts-not-hinted/GHGuardianHeadline-MediumItalic.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/latin1-not-hinted/GHGuardianHeadline-MediumItalic.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/latin1-not-hinted/GHGuardianHeadline-MediumItalic.ttf)
        format("truetype");
    font-weight: 500;
    font-style: italic;
    font-display: swap;
  }
  @font-face {
    font-family: "GH Guardian Headline";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/noalts-not-hinted/GHGuardianHeadline-Bold.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/latin1-not-hinted/GHGuardianHeadline-Bold.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/latin1-not-hinted/GHGuardianHeadline-Bold.ttf)
        format("truetype");
    font-weight: 700;
    font-style: normal;
    font-display: swap;
  }
  @font-face {
    font-family: "GH Guardian Headline";
    src:
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/noalts-not-hinted/GHGuardianHeadline-BoldItalic.woff2)
        format("woff2"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/latin1-not-hinted/GHGuardianHeadline-BoldItalic.woff)
        format("woff"),
      url(https://assets.guim.co.uk/static/frontend/fonts/guardian-headline/latin1-not-hinted/GHGuardianHeadline-BoldItalic.ttf)
        format("truetype");
    font-weight: 700;
    font-style: italic;
    font-display: swap;
  }
  @font-face {
    font-family: "GH Guardian Headline";
    src:
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GHGuardianHeadline/GHGuardianHeadline-Bold.woff2")
        format("woff2"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GHGuardianHeadline/GHGuardianHeadline-Bold.woff")
        format("woff"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GHGuardianHeadline/GHGuardianHeadline-Bold.ttf")
        format("truetype");
    font-weight: 700;
    font-style: normal;
    font-stretch: normal;
  }
  @font-face {
    font-family: "GH Guardian Headline";
    src:
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GHGuardianHeadline/GHGuardianHeadline-Regular.woff2")
        format("woff2"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GHGuardianHeadline/GHGuardianHeadline-Regular.woff")
        format("woff"),
      url("https://interactive.guim.co.uk/fonts/guss-webfonts/GHGuardianHeadline/GHGuardianHeadline-Regular.ttf")
        format("truetype");
    font-weight: 400;
    font-style: normal;
    font-stretch: normal;
  }
</style>
